Repository skiprco/go-utils, pull requests merged in 2021-02, with the labels that each got.

#36 mongo-library
  README.md
  go.mod
  mongo/mongoRepository.go
Labels: v2.8.2

#38 mongo mock
  mongo/mocks/IMongoRepository.go
Labels: v2.8.3

#39 Metadata: Add GetUserIDFromGoMicroMeta helper
  README.md
  metadata/constants.go
  metadata/go_micro_helpers.go
Labels: v2.9.0

#37 Refactor roles check
  README.md
  auth/constants.go
  auth/roles.go
  auth/roles_helpers.go
  auth/roles_test.go
Labels: v2.10.0
