Repository skiprco/go-utils, pull requests merged in 2021-01, with the labels that each got.

#26 adds phone_number validation
  go.mod
  validation/phone_number.go
  validation/phone_number_test.go
Labels: v2.2.0

#27 Add docstring to ValidateAndFormatPhoneNumber
  validation/phone_number.go
Labels: v2.2.0

#29 Add docs for ValidateAndFormatPhoneNumber
  README.md
Labels: v2.3.0

#28 Include response body on response_code_is_error
  README.md
  errors/genericError.go
  errors/genericError_test.go
  http/http.go
  http/http_test.go
Labels: v2.3.0

#30 Add UnwrapResponseCodeIsError
  README.md
  http/http.go
Labels: v2.4.0

#31 add clean Phone number function
  converters/phone_number.go
  converters/phone_number_test.go
Labels: 2.5.0

#32 Validation: Add WithinTimeRange
  README.md
  validation/time.go
  validation/time_test.go
Labels: v2.6.0

#33 adds cleanSpecialCharacters
  README.md
  converters/strings.go
  converters/strings_test.go
Labels: v2.7.0
